name: weekly_schedule
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2 # Save data
  flutter_slidable: ^3.0.1 # قابل للانزلاق
  showcaseview: ^2.0.3 # هو مكتبة تسمح للمطورين بإظهار نقاط تعريف للمستخدمين في التطبيق الخاص بهم

        #  شاشة البداية
  flutter_native_splash: ^2.2.14
  intl: any
flutter_native_splash:
  color: "#ffffff"
  # image: "assets/images/app/"
  image_path: "assets/images/splash-app/"

  android_gravity: center
  # في حاله الوضع المظلم 
  color_dark: "#bbd0ff"
  android: true
  ios: true
  # بعد كده اعمل رن للاوامر دي
  # flutter clean 
  # flutter pub get
  # flutter pub run flutter_native_splash:create

dev_dependencies:
#  لي اضافه اللغه العربيه داخل التطبيق
  flutter_test:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line


  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/splash-app/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
